### PR TITLE
Inventory names

### PR DESCRIPTION
**Pull request by CharlesBeise**
Gave each item file an "inventoryName" to display in the inventory name. (e.g., instead of "flashlight2" it will just display "Flashlight" for all 3 flashlights.)

### CODE REVIEW

**Review by SaphiraSkies — CHANGES_REQUESTED** [review]
Does this mean we're using the specific terms "Polaroid", "dusty Polaroid", and "old Polaroid" to distinguish between the three from this point on?

In other words, is it being changed only to be a display name, or does the player have to enter those specific phrases to interact with one of the polaroids?

Does there need to be something that translates "dusty Polaroid" into "polaroid3"? Do changes need to be made with the identifyPolaroid function?

**Comment by CharlesBeise** [comment]
Good questions!

Yes, identifyPolaroid will have to be changed, I have been working on the changes and I think I have something that isn't too bad. I'll add those changes to this PR.

The names are not set in stone, and I am very open to suggestions for better names for the polaroids. I just wanted to put something down for now that doesn't reveal how many polaroids the player needs to find.

**Comment by CharlesBeise** [comment]
I think using identifyPolaroid will make the game feel more immersive, mainly for when the player only has one polaroid in their possession. For example, if they only have "Old Polaroid" and they type "Flip the polaroid" then the game will go ahead and tell them the response for "Old Polaroid", whereas with the dictionary approach the game would give them an error message.

**Review by SaphiraSkies — APPROVED** [review]
All good!

**Pull request merged**
