### PR TITLE
More fixes

### PR DESCRIPTION
**Pull request by SaphiraSkies**
Had a friend test the game.

Fixed:
- some compound words were missing
- polaroid selection was confused with command entry
- items could be used on features not located in the current room

### CODE REVIEW

**Review by CharlesBeise — APPROVED** [review]
Nice catches!

**Comment by CharlesBeise** [comment]
Oops, I'll wait to merge. Just saw your comment

**Comment by SaphiraSkies** [comment]
Nevermind, we're good to go. Had to test some things first.

**Review by CharlesBeise — APPROVED** [review]
Looks good!

**Pull request merged**
